--------------------------------------------------------
-- Archivo creado  - miércoles-septiembre-19-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "USUARIO_JAVA"."CLIENTE" 
   (	"ID_CLIENTE" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APELLIDO" VARCHAR2(100 BYTE), 
	"RAZON_SOCIAL" VARCHAR2(100 BYTE), 
	"NIT" VARCHAR2(10 BYTE), 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"TELEFONO" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"FECHA_INGRESO" DATE, 
	"ESTATUS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTAMENTO
--------------------------------------------------------

  CREATE TABLE "USUARIO_JAVA"."DEPARTAMENTO" 
   (	"ID_DEPARTAMENTO" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(80 BYTE), 
	"ESTADO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "USUARIO_JAVA"."EMPLEADO" 
   (	"ID_EMPLEADO" NUMBER(*,0), 
	"PRIMER_NOMBRE" VARCHAR2(100 BYTE), 
	"SEGUNDO_NOMBRE" VARCHAR2(100 BYTE), 
	"PRIMER_APELLIDO" VARCHAR2(100 BYTE), 
	"SEGUNDO_APELLIDO" VARCHAR2(100 BYTE), 
	"NIT" VARCHAR2(10 BYTE), 
	"SALARIO" NUMBER(*,0), 
	"ESTATUS" NUMBER(*,0), 
	"ID_DEPARTAMENTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FACTURA
--------------------------------------------------------

  CREATE TABLE "USUARIO_JAVA"."FACTURA" 
   (	"ID_FACTURA" NUMBER(*,0), 
	"NO_FACT" NUMBER(*,0), 
	"SERIE" VARCHAR2(20 BYTE), 
	"ID_CLIENTE" NUMBER(*,0), 
	"ID_EMPLEADO" NUMBER(*,0), 
	"FECHA_FAC" DATE, 
	"ESTADO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FACTURA_DETALLE
--------------------------------------------------------

  CREATE TABLE "USUARIO_JAVA"."FACTURA_DETALLE" 
   (	"ID_FACTURA" NUMBER(*,0), 
	"ID_LINEA" NUMBER(*,0), 
	"ID_PRODUCTO" NUMBER(*,0), 
	"CANTIDAD" NUMBER(*,0), 
	"ESTADO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FECHA
--------------------------------------------------------

  CREATE TABLE "USUARIO_JAVA"."FECHA" 
   (	"ID_FECHA" NUMBER(*,0), 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "USUARIO_JAVA"."PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER(*,0), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"STOCK" NUMBER(*,0), 
	"STOCK_MINIMO" NUMBER(*,0), 
	"PRECIO_UNITARIO" FLOAT(126), 
	"ID_PROVEEDOR" NUMBER(*,0), 
	"ESTADO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "USUARIO_JAVA"."PROVEEDOR" 
   (	"ID_PROVEEDOR" NUMBER(*,0), 
	"EMPRESA" VARCHAR2(100 BYTE), 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"TELEFONO" NUMBER(*,0), 
	"NIT" VARCHAR2(30 BYTE), 
	"CIUDAD" VARCHAR2(100 BYTE), 
	"PAIS" VARCHAR2(100 BYTE), 
	"CONTACTO" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"TELEFONO_CONTACTO" NUMBER(*,0), 
	"ESTATUS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "USUARIO_JAVA"."USUARIO" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"USUARIO" VARCHAR2(100 BYTE), 
	"CONTRASENA" VARCHAR2(100 BYTE), 
	"FECHA_INGRESO" DATE, 
	"FECHA_ULTIMA_MODIFICACION" DATE, 
	"ID_EMPLEADO" NUMBER(*,0), 
	"ESTADO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into USUARIO_JAVA.CLIENTE
SET DEFINE OFF;
Insert into USUARIO_JAVA.CLIENTE (ID_CLIENTE,NOMBRE,APELLIDO,RAZON_SOCIAL,NIT,DIRECCION,TELEFONO,EMAIL,FECHA_INGRESO,ESTATUS) values (2,'Roberto','Velasquez','soltero','16329783','Colonia Vista el valle','123456789','jairo.j5180@gmail.com',to_date('02/09/18','DD/MM/RR'),1);
Insert into USUARIO_JAVA.CLIENTE (ID_CLIENTE,NOMBRE,APELLIDO,RAZON_SOCIAL,NIT,DIRECCION,TELEFONO,EMAIL,FECHA_INGRESO,ESTATUS) values (1,'Jairo','Velasquez','Soltero','123456444','Salama Baja Verapaz','123456788','jairo.j5180@gmail.com',to_date('18/09/18','DD/MM/RR'),1);
Insert into USUARIO_JAVA.CLIENTE (ID_CLIENTE,NOMBRE,APELLIDO,RAZON_SOCIAL,NIT,DIRECCION,TELEFONO,EMAIL,FECHA_INGRESO,ESTATUS) values (3,'Ernesto','Sical','soltero','1111111111','San Jeronimo Baja Verapaz','12453152','ernerto@gmail.com',to_date('22/09/18','DD/MM/RR'),1);
REM INSERTING into USUARIO_JAVA.DEPARTAMENTO
SET DEFINE OFF;
Insert into USUARIO_JAVA.DEPARTAMENTO (ID_DEPARTAMENTO,DESCRIPCION,ESTADO) values (3,'Recursos Hmanos',1);
Insert into USUARIO_JAVA.DEPARTAMENTO (ID_DEPARTAMENTO,DESCRIPCION,ESTADO) values (5,'informatica',1);
Insert into USUARIO_JAVA.DEPARTAMENTO (ID_DEPARTAMENTO,DESCRIPCION,ESTADO) values (1,'Informatica',1);
Insert into USUARIO_JAVA.DEPARTAMENTO (ID_DEPARTAMENTO,DESCRIPCION,ESTADO) values (2,'prueba 2',1);
Insert into USUARIO_JAVA.DEPARTAMENTO (ID_DEPARTAMENTO,DESCRIPCION,ESTADO) values (4,'Enfermeria',1);
Insert into USUARIO_JAVA.DEPARTAMENTO (ID_DEPARTAMENTO,DESCRIPCION,ESTADO) values (6,'Administracion',1);
REM INSERTING into USUARIO_JAVA.EMPLEADO
SET DEFINE OFF;
Insert into USUARIO_JAVA.EMPLEADO (ID_EMPLEADO,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,NIT,SALARIO,ESTATUS,ID_DEPARTAMENTO) values (1,'Jairo','Roberto1','Velásquez','zuniga','16329783',1000,0,5);
Insert into USUARIO_JAVA.EMPLEADO (ID_EMPLEADO,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,NIT,SALARIO,ESTATUS,ID_DEPARTAMENTO) values (2,'q','q','q','q','1',500000,1,5);
Insert into USUARIO_JAVA.EMPLEADO (ID_EMPLEADO,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,NIT,SALARIO,ESTATUS,ID_DEPARTAMENTO) values (3,'Luis','Eduardo','Lopez','Lopez','1234521521',1000,1,6);
Insert into USUARIO_JAVA.EMPLEADO (ID_EMPLEADO,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,NIT,SALARIO,ESTATUS,ID_DEPARTAMENTO) values (4,'prueba','prueba','prueba','prueba','1112212022',100000,1,1);
REM INSERTING into USUARIO_JAVA.FACTURA
SET DEFINE OFF;
REM INSERTING into USUARIO_JAVA.FACTURA_DETALLE
SET DEFINE OFF;
REM INSERTING into USUARIO_JAVA.FECHA
SET DEFINE OFF;
Insert into USUARIO_JAVA.FECHA (ID_FECHA,FECHA) values (1,null);
Insert into USUARIO_JAVA.FECHA (ID_FECHA,FECHA) values (4,to_date('17/09/18','DD/MM/RR'));
Insert into USUARIO_JAVA.FECHA (ID_FECHA,FECHA) values (5,to_date('20/09/18','DD/MM/RR'));
Insert into USUARIO_JAVA.FECHA (ID_FECHA,FECHA) values (6,to_date('21/09/18','DD/MM/RR'));
Insert into USUARIO_JAVA.FECHA (ID_FECHA,FECHA) values (7,to_date('23/09/18','DD/MM/RR'));
Insert into USUARIO_JAVA.FECHA (ID_FECHA,FECHA) values (8,to_date('30/09/18','DD/MM/RR'));
Insert into USUARIO_JAVA.FECHA (ID_FECHA,FECHA) values (9,to_date('05/09/18','DD/MM/RR'));
Insert into USUARIO_JAVA.FECHA (ID_FECHA,FECHA) values (10,to_date('05/12/19','DD/MM/RR'));
Insert into USUARIO_JAVA.FECHA (ID_FECHA,FECHA) values (11,to_date('07/09/18','DD/MM/RR'));
Insert into USUARIO_JAVA.FECHA (ID_FECHA,FECHA) values (3,to_date('18/09/18','DD/MM/RR'));
Insert into USUARIO_JAVA.FECHA (ID_FECHA,FECHA) values (2,to_date('17/09/18','DD/MM/RR'));
Insert into USUARIO_JAVA.FECHA (ID_FECHA,FECHA) values (12,to_date('05/09/18','DD/MM/RR'));
REM INSERTING into USUARIO_JAVA.PRODUCTO
SET DEFINE OFF;
Insert into USUARIO_JAVA.PRODUCTO (ID_PRODUCTO,DESCRIPCION,STOCK,STOCK_MINIMO,PRECIO_UNITARIO,ID_PROVEEDOR,ESTADO) values (1,'Pan Bimbo',100,10,15,1,1);
Insert into USUARIO_JAVA.PRODUCTO (ID_PRODUCTO,DESCRIPCION,STOCK,STOCK_MINIMO,PRECIO_UNITARIO,ID_PROVEEDOR,ESTADO) values (3,'Sopas Laky',500,10,5,2,1);
REM INSERTING into USUARIO_JAVA.PROVEEDOR
SET DEFINE OFF;
Insert into USUARIO_JAVA.PROVEEDOR (ID_PROVEEDOR,EMPRESA,DIRECCION,TELEFONO,NIT,CIUDAD,PAIS,CONTACTO,EMAIL,TELEFONO_CONTACTO,ESTATUS) values (1,'BIMBO','CIUDAD1',54784854,'14789562','GUATEMALA','GUATEMALA','CONTACTO','bimbo',11111111,1);
Insert into USUARIO_JAVA.PROVEEDOR (ID_PROVEEDOR,EMPRESA,DIRECCION,TELEFONO,NIT,CIUDAD,PAIS,CONTACTO,EMAIL,TELEFONO_CONTACTO,ESTATUS) values (2,'laky','ciudad',12345678,'16329871','ciudad','guatemala','12345678','laky',12345678,1);
Insert into USUARIO_JAVA.PROVEEDOR (ID_PROVEEDOR,EMPRESA,DIRECCION,TELEFONO,NIT,CIUDAD,PAIS,CONTACTO,EMAIL,TELEFONO_CONTACTO,ESTATUS) values (3,'TIGO','CIUDAD',12345678,'12345678','salama333','guatemala','guatemala','prueba@gmail.com',1234,1);
REM INSERTING into USUARIO_JAVA.USUARIO
SET DEFINE OFF;
Insert into USUARIO_JAVA.USUARIO (ID_USUARIO,USUARIO,CONTRASENA,FECHA_INGRESO,FECHA_ULTIMA_MODIFICACION,ID_EMPLEADO,ESTADO) values (1,'Jairo','.',to_date('04/09/18','DD/MM/RR'),to_date('19/09/18','DD/MM/RR'),1,0);
Insert into USUARIO_JAVA.USUARIO (ID_USUARIO,USUARIO,CONTRASENA,FECHA_INGRESO,FECHA_ULTIMA_MODIFICACION,ID_EMPLEADO,ESTADO) values (2,'JairoVel','pass',to_date('19/09/18','DD/MM/RR'),to_date('19/09/18','DD/MM/RR'),1,1);
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_CLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."ACTUALIZAR_CLIENTE" (
IDE IN INT, NOM IN VARCHAR2, APE IN VARCHAR2, RAZON IN VARCHAR2, NITS IN VARCHAR2,
DIRE IN VARCHAR2, TEL IN VARCHAR2, EMAILS IN VARCHAR2, FECHA IN DATE, EST IN INT
    )
AS

BEGIN


UPDATE CLIENTE SET NOMBRE=NOM,APELLIDO=APE,RAZON_SOCIAL=RAZON,NIT=NITS,DIRECCION=DIRE,TELEFONO=TEL,EMAIL=EMAILS,FECHA_INGRESO=FECHA WHERE ID_CLIENTE=IDE;

END ACTUALIZAR_CLIENTE;

/
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_DEPARTAMENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."ACTUALIZAR_DEPARTAMENTO" (
IDE IN INT,		NOMBRE IN VARCHAR2
    )
AS

BEGIN


UPDATE DEPARTAMENTO SET DESCRIPCION=NOMBRE WHERE ID_DEPARTAMENTO=IDE;

END ACTUALIZAR_DEPARTAMENTO;

/
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_EMPLEADO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."ACTUALIZAR_EMPLEADO" (
IDE IN INT,
PRIMER_N IN VARCHAR2,
SEGUNDO_N IN VARCHAR2,
PRIMER_A IN VARCHAR2,
SEGUNDO_A IN VARCHAR2,
NITS IN VARCHAR2, 
SALARI IN INT,
ID_DEP IN INT)
AS

BEGIN
UPDATE EMPLEADO SET PRIMER_NOMBRE=PRIMER_N,SEGUNDO_NOMBRE=SEGUNDO_N,PRIMER_APELLIDO=PRIMER_A,SEGUNDO_APELLIDO=SEGUNDO_A,NIT=NITS,SALARIO=SALARI,ID_DEPARTAMENTO=ID_DEP WHERE ID_EMPLEADO=IDE;
END ACTUALIZAR_EMPLEADO;

/
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_FACTURA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."ACTUALIZAR_FACTURA" (
IDE IN INT, NO_FA IN INT,SERI IN VARCHAR2,ID_CLI IN INT,ID_EMPLE IN INT,FECHA IN DATE)
AS
BEGIN
UPDATE FACTURA SET NO_FACT=NO_FA,SERIE=SERI,ID_CLIENTE=ID_CLI,ID_EMPLEADO=ID_EMPLE,FECHA_FAC=FECHA WHERE ID_FACTURA=IDE;
END ACTUALIZAR_FACTURA;

/
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_FACTURA_DETALLE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."ACTUALIZAR_FACTURA_DETALLE" (
IDE IN INT,ID_LIN IN INT,ID_PROD IN INT,CANT IN INT)
AS
BEGIN
UPDATE FACTURA_DETALLE SET ID_LINEA=ID_LIN,ID_PRODUCTO=ID_PROD,CANTIDAD=CANT WHERE ID_FACTURA=IDE;
END ACTUALIZAR_FACTURA_DETALLE;

/
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_PRODUCTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."ACTUALIZAR_PRODUCTO" (
IDE IN INT,DESCRIP IN VARCHAR2,STOC IN INT, STOCK_MINI IN VARCHAR2, PRECIO IN FLOAT, ID_PROVE IN INT, EST IN INT
    )
AS

BEGIN


UPDATE PRODUCTO SET DESCRIPCION=DESCRIP,STOCK=STOC,STOCK_MINIMO=STOCK_MINI,PRECIO_UNITARIO=PRECIO WHERE ID_PRODUCTO=IDE;

END ACTUALIZAR_PRODUCTO;

/
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_PROVEEDOR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."ACTUALIZAR_PROVEEDOR" (
IDE IN INT,EMPRE IN VARCHAR2, DIRE IN VARCHAR2, TEL IN INT, NITS IN VARCHAR2, CIU IN VARCHAR2, PAIZ IN VARCHAR2,
CONTAC IN VARCHAR2, EMAILS IN VARCHAR2, TEL_CONTACTO IN INT)
AS

BEGIN

UPDATE PROVEEDOR SET EMPRESA=EMPRE,DIRECCION=DIRE,TELEFONO=TEL,NIT=NITS,CIUDAD=CIU,PAIS=PAIZ,CONTACTO=CONTAC,EMAIL=EMAILS,TELEFONO_CONTACTO=TEL_CONTACTO WHERE ID_PROVEEDOR=IDE;

END ACTUALIZAR_PROVEEDOR;

/
--------------------------------------------------------
--  DDL for Procedure ACTUALIZAR_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."ACTUALIZAR_USUARIO" (
IDE IN INT,USU IN VARCHAR2,PASS IN VARCHAR2,FECHA_I IN DATE,FECHA_U IN DATE,ID_EMP IN INT)
AS
BEGIN
UPDATE USUARIO SET USUARIO=USU,CONTRASENA=PASS,FECHA_INGRESO=FECHA_I,FECHA_ULTIMA_MODIFICACION=FECHA_U,ID_EMPLEADO=ID_EMP WHERE ID_USUARIO = IDE;
END ACTUALIZAR_USUARIO;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_CLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."ELIMINAR_CLIENTE" (
IDE IN INT, EST IN INT
)
AS

BEGIN 
    UPDATE CLIENTE SET ESTATUS = EST WHERE ID_CLIENTE = IDE;
END ELIMINAR_CLIENTE;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_DEPARTAMENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."ELIMINAR_DEPARTAMENTO" (
IDE IN INT, EST IN INT
    )
AS

BEGIN


UPDATE DEPARTAMENTO SET ESTADO=EST WHERE ID_DEPARTAMENTO=IDE;

END ELIMINAR_DEPARTAMENTO;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_EMPLEADO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."ELIMINAR_EMPLEADO" (
IDE IN INT, EST IN INT)
AS
BEGIN
UPDATE EMPLEADO SET ESTATUS=EST WHERE ID_EMPLEADO=IDE;
END ELIMINAR_EMPLEADO;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_FACTURA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."ELIMINAR_FACTURA" (
IDE IN INT,EST IN INT)
AS
BEGIN
UPDATE FACTURA SET ESTADO=EST WHERE ID_FACTURA=IDE;
END ELIMINAR_FACTURA;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_FACTURA_DETALLE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."ELIMINAR_FACTURA_DETALLE" (IDE IN INT, EST IN INT)
AS
BEGIN
UPDATE FACTURA_DETALLE SET ESTADO = EST WHERE ID_FACTURA=IDE;
END ELIMINAR_FACTURA_DETALLE;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_PRODUCTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."ELIMINAR_PRODUCTO" (
IDE IN INT, EST IN INT
    )
AS

BEGIN

UPDATE PRODUCTO SET ESTADO=EST WHERE ID_PRODUCTO=IDE;

END ELIMINAR_PRODUCTO;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_PROVEEDOR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."ELIMINAR_PROVEEDOR" (
IDE IN INT, ESTA IN INT)
AS

BEGIN

UPDATE PROVEEDOR SET ESTATUS=ESTA WHERE ID_PROVEEDOR=IDE;

END ELIMINAR_PROVEEDOR;

/
--------------------------------------------------------
--  DDL for Procedure ELIMINAR_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."ELIMINAR_USUARIO" (
IDE  IN INT, EST IN INT)
AS
BEGIN
UPDATE USUARIO SET ESTADO=EST WHERE ID_USUARIO=IDE;
END ELIMINAR_USUARIO;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_CLIENTE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."INSERTAR_CLIENTE" (
IDE IN INT, NOM IN VARCHAR2, APE IN VARCHAR2, RAZON IN VARCHAR2, NITS IN VARCHAR2,
DIRE IN VARCHAR2, TEL IN VARCHAR2, EMAILS IN VARCHAR2, FECHA IN DATE, EST IN INT
)

AS

BEGIN
INSERT INTO CLIENTE
    (ID_CLIENTE,NOMBRE,APELLIDO,RAZON_SOCIAL,NIT,DIRECCION,TELEFONO,EMAIL,FECHA_INGRESO,ESTATUS)
    VALUES (IDE,NOM,APE,RAZON,NITS,DIRE,TEL,EMAILS,FECHA,EST);
END INSERTAR_CLIENTE;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_DEPARTAMENTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."INSERTAR_DEPARTAMENTO" (
IDE IN INT,		NOMBRE IN VARCHAR2, EST IN INT
    )
AS

BEGIN


INSERT INTO DEPARTAMENTO
 (ID_DEPARTAMENTO,DESCRIPCION,ESTADO)
 VALUES (IDE,NOMBRE,EST);
END INSERTAR_DEPARTAMENTO;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_EMPLEADO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."INSERTAR_EMPLEADO" (
IDE IN INT, 
PRIMER_N IN VARCHAR2,
SEGUNDO_N IN VARCHAR2,
PRIMER_A IN VARCHAR2, 
SEGUNDO_A IN VARCHAR2,
NITS IN VARCHAR2, 
SALARI IN INT,
EST IN INT, 
ID_DEP IN INT)
AS

BEGIN
INSERT INTO EMPLEADO(ID_EMPLEADO,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,NIT,SALARIO,ESTATUS,ID_DEPARTAMENTO)
VALUES(IDE,PRIMER_N,SEGUNDO_N,PRIMER_A,SEGUNDO_A,NITS,SALARI,EST,ID_DEP);
END INSERTAR_EMPLEADO;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_FACTURA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."INSERTAR_FACTURA" (
IDE IN INT, NO_FA IN INT,SERI IN VARCHAR2,ID_CLI IN INT,ID_EMPLE IN INT,FECHA IN DATE,EST IN INT)
AS
BEGIN
INSERT INTO FACTURA(ID_FACTURA,NO_FACT,SERIE,ID_CLIENTE,ID_EMPLEADO,FECHA_FAC,ESTADO)
VALUES(IDE,NO_FA,SERI,ID_CLI,ID_EMPLE,FECHA,EST);
END INSERTAR_FACTURA;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_FACTURA_DETALLE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."INSERTAR_FACTURA_DETALLE" (
IDE IN INT,ID_LIN IN INT,ID_PROD IN INT,CANT IN INT,EST IN INT)
AS

BEGIN
INSERT INTO FACTURA_DETALLE(ID_FACTURA,ID_LINEA,ID_PRODUCTO,CANTIDAD,ESTADO)
VALUES(IDE,ID_LIN,ID_PROD,CANT,EST);
END INSERTAR_FACTURA_DETALLE;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_FECHA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."INSERTAR_FECHA" (
IDE IN INT, FEC IN DATE
    )
AS

BEGIN


INSERT INTO FECHA
 (ID_FECHA,FECHA)
 VALUES (IDE, FEC);
END INSERTAR_FECHA;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_PRODUCTO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."INSERTAR_PRODUCTO" (
IDE IN INT,DESCRIP IN VARCHAR2,STOC IN INT, STOCK_MINI IN VARCHAR2, PRECIO IN FLOAT, ID_PROVE IN INT, EST IN INT
)
AS

BEGIN
INSERT INTO PRODUCTO(ID_PRODUCTO,DESCRIPCION,STOCK,STOCK_MINIMO,PRECIO_UNITARIO,ID_PROVEEDOR,ESTADO)
 VALUES (IDE,DESCRIP,STOC,STOCK_MINI,PRECIO,ID_PROVE,EST);
END INSERTAR_PRODUCTO;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_PROVEEDOR
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."INSERTAR_PROVEEDOR" (
IDE IN INT,EMPRE IN VARCHAR2, DIRE IN VARCHAR2, TEL IN INT, NITS IN VARCHAR2, CIU IN VARCHAR2, PAIZ IN VARCHAR2,
CONTAC IN VARCHAR2, EMAILS IN VARCHAR2, TEL_CONTACTO IN INT, ESTA IN INT)
AS

BEGIN
INSERT INTO PROVEEDOR(ID_PROVEEDOR,EMPRESA,DIRECCION,TELEFONO,NIT,CIUDAD,PAIS,CONTACTO,EMAIL,TELEFONO_CONTACTO,ESTATUS)
 VALUES (IDE,EMPRE,DIRE,TEL,NITS,CIU,PAIZ,CONTAC,EMAILS,TEL_CONTACTO,ESTA);
END INSERTAR_PROVEEDOR;

/
--------------------------------------------------------
--  DDL for Procedure INSERTAR_USUARIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "USUARIO_JAVA"."INSERTAR_USUARIO" (
IDE IN INT,USU IN VARCHAR2,PASS IN VARCHAR2,FECHA_I IN DATE,FECHA_U IN DATE,ID_EMP IN INT,EST IN INT)
AS
BEGIN
INSERT INTO USUARIO(ID_USUARIO,USUARIO,CONTRASENA,FECHA_INGRESO,FECHA_ULTIMA_MODIFICACION,ID_EMPLEADO,ESTADO)VALUES(IDE, USU,PASS,FECHA_I,FECHA_U,ID_EMP, EST);
END INSERTAR_USUARIO;

/
--------------------------------------------------------
--  DDL for Package CLIENTE_MAX
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE "USUARIO_JAVA"."CLIENTE_MAX" 
AS  
    TYPE salida_out IS REF CURSOR;
    PROCEDURE AUTO_INCREMENT(salida out salida_out);

end;

/
--------------------------------------------------------
--  DDL for Package Body CLIENTE_MAX
--------------------------------------------------------

  CREATE OR REPLACE PACKAGE BODY "USUARIO_JAVA"."CLIENTE_MAX" 
AS
    PROCEDURE AUTO_INCREMENT(salida out salida_out)
    IS  
        BEGIN   
            OPEN salida for
                select coalesce(MAX(id_cliente), 0)+1 id from cliente;
                end;

end;

/
--------------------------------------------------------
--  Constraints for Table PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "USUARIO_JAVA"."PROVEEDOR" ADD PRIMARY KEY ("ID_PROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "USUARIO_JAVA"."USUARIO" ADD PRIMARY KEY ("USUARIO", "CONTRASENA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACTURA
--------------------------------------------------------

  ALTER TABLE "USUARIO_JAVA"."FACTURA" ADD PRIMARY KEY ("ID_FACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FACTURA_DETALLE
--------------------------------------------------------

  ALTER TABLE "USUARIO_JAVA"."FACTURA_DETALLE" ADD PRIMARY KEY ("ID_FACTURA", "ID_LINEA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "USUARIO_JAVA"."EMPLEADO" ADD PRIMARY KEY ("ID_EMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "USUARIO_JAVA"."PRODUCTO" ADD PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FECHA
--------------------------------------------------------

  ALTER TABLE "USUARIO_JAVA"."FECHA" ADD PRIMARY KEY ("ID_FECHA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEPARTAMENTO
--------------------------------------------------------

  ALTER TABLE "USUARIO_JAVA"."DEPARTAMENTO" ADD PRIMARY KEY ("ID_DEPARTAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "USUARIO_JAVA"."CLIENTE" ADD PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "USUARIO_JAVA"."EMPLEADO" ADD FOREIGN KEY ("ID_DEPARTAMENTO")
	  REFERENCES "USUARIO_JAVA"."DEPARTAMENTO" ("ID_DEPARTAMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACTURA
--------------------------------------------------------

  ALTER TABLE "USUARIO_JAVA"."FACTURA" ADD FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "USUARIO_JAVA"."CLIENTE" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "USUARIO_JAVA"."FACTURA" ADD FOREIGN KEY ("ID_EMPLEADO")
	  REFERENCES "USUARIO_JAVA"."EMPLEADO" ("ID_EMPLEADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "USUARIO_JAVA"."PRODUCTO" ADD FOREIGN KEY ("ID_PROVEEDOR")
	  REFERENCES "USUARIO_JAVA"."PROVEEDOR" ("ID_PROVEEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "USUARIO_JAVA"."USUARIO" ADD FOREIGN KEY ("ID_EMPLEADO")
	  REFERENCES "USUARIO_JAVA"."EMPLEADO" ("ID_EMPLEADO") ENABLE;
