/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import conexion.CreateConnection;
import constans.AppConstasQry;
import java.awt.HeadlessException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utils.Funciones;

/**
 *
 * @author JairoDev
 */
public class EmpleadoInternal extends javax.swing.JInternalFrame {

    Connection cn;
    CallableStatement cts;
    ResultSet r;
    CreateConnection conectar = new CreateConnection();
    Vector columnNames;
    Vector data;
    Statement stmt;
    String qry = null;
    /**
     * Creates new form EmpleadoInternal
     */
    DefaultTableModel modelo = new DefaultTableModel();

    public EmpleadoInternal() throws SQLException {
        initComponents();
        this.data = new Vector();
        this.columnNames = new Vector();
        initComponents();
        this.stmt = null;
        this.jTableEmpleado.setModel(modelo);
        cn = conectar.getConnection();
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogDepartamento = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDep = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleado = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lvlApellido = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        txtNit = new javax.swing.JTextField();
        lblNit = new javax.swing.JLabel();
        lblDire = new javax.swing.JLabel();
        txtDep = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNombre2 = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        lvlApellido1 = new javax.swing.JLabel();
        txtApellido2 = new javax.swing.JTextField();
        btnBuscarDep = new javax.swing.JButton();

        jDialogDepartamento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jDialogDepartamento.setLocationByPlatform(true);
        jDialogDepartamento.setMinimumSize(new java.awt.Dimension(665, 419));
        jDialogDepartamento.setModal(true);
        jDialogDepartamento.setResizable(false);

        jTableDep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableDep);

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogDepartamentoLayout = new javax.swing.GroupLayout(jDialogDepartamento.getContentPane());
        jDialogDepartamento.getContentPane().setLayout(jDialogDepartamentoLayout);
        jDialogDepartamentoLayout.setHorizontalGroup(
            jDialogDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDepartamentoLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jButton1)
                .addGap(139, 139, 139)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogDepartamentoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialogDepartamentoLayout.setVerticalGroup(
            jDialogDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogDepartamentoLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jDialogDepartamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        setClosable(true);
        setIconifiable(true);

        jTableEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleado);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mantenimiento Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(204, 0, 51))); // NOI18N

        lblCodigo.setText("ID EMPLEADO");

        lblNombre.setText("Primer Nombre:");

        lvlApellido.setText("Primer Apellido");

        lblTelefono.setText("Salario");

        txtId.setEnabled(false);
        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        txtNombre1.setEnabled(false);
        txtNombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre1KeyTyped(evt);
            }
        });

        txtApellido1.setEnabled(false);
        txtApellido1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellido1KeyTyped(evt);
            }
        });

        txtSalario.setEnabled(false);
        txtSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalarioKeyTyped(evt);
            }
        });

        txtNit.setEnabled(false);
        txtNit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNitKeyTyped(evt);
            }
        });

        lblNit.setText("Nit:");

        lblDire.setText("Departamento");

        txtDep.setEnabled(false);
        txtDep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDepKeyTyped(evt);
            }
        });

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Calcelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtNombre2.setEnabled(false);
        txtNombre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre2KeyTyped(evt);
            }
        });

        lblNombre1.setText("Segundo Nombre");

        lvlApellido1.setText("Segundo Apellido");

        txtApellido2.setEnabled(false);
        txtApellido2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellido2KeyTyped(evt);
            }
        });

        btnBuscarDep.setText("B");
        btnBuscarDep.setEnabled(false);
        btnBuscarDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNit)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(73, 73, 73)
                                    .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblDire)
                                        .addComponent(lvlApellido)))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtDep, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lvlApellido1)
                                .addGap(29, 29, 29)
                                .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNombre1)
                                .addGap(29, 29, 29)
                                .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTelefono)
                                .addGap(29, 29, 29)
                                .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBuscarDep, javax.swing.GroupLayout.Alignment.LEADING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnGuardar)
                        .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar)
                    .addComponent(btnBuscar))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigo)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre1)
                            .addComponent(txtNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lvlApellido)
                            .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lvlApellido1)
                            .addComponent(txtApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNit)
                            .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefono)
                            .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDire)
                            .addComponent(btnBuscarDep)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnCancelar))
                        .addGap(18, 18, 18)
                        .addComponent(btnModificar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdKeyReleased

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped

    }//GEN-LAST:event_txtIdKeyTyped

    private void txtNombre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre1KeyTyped
        Funciones.valCampoTexto(evt);
    }//GEN-LAST:event_txtNombre1KeyTyped

    private void txtApellido1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido1KeyTyped
        Funciones.valCampoTexto(evt);
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido1KeyTyped

    private void txtSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalarioKeyTyped
        Funciones.valCampoTel(evt, this.txtSalario.getText());
    }//GEN-LAST:event_txtSalarioKeyTyped

    private void txtNitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNitKeyTyped
        // TODO add your handling code here:
        Funciones.valCampoNit(evt, this.txtNit.getText());
    }//GEN-LAST:event_txtNitKeyTyped

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
        obtenerId();
        habilitar();
        btnNuevo.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnBuscar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnBuscarDep.setEnabled(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.buscarEmpleado();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked

    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        insertarEmpleado();
        mostrarDatos();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        this.modificarEmpleado();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        this.eliminarEmpleado();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limpiar();
        this.desabilitar();
        this.btnGuardar.setEnabled(false);
        this.btnNuevo.setEnabled(true);
        this.btnCancelar.setEnabled(false);
        this.btnBuscar.setEnabled(true);
        this.btnEliminar.setEnabled(false);
        this.btnModificar.setEnabled(false);
        this.btnBuscarDep.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre2KeyTyped

    private void txtApellido2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellido2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellido2KeyTyped

    private void btnBuscarDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDepActionPerformed
        try {
            mostarDepartamento();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnBuscarDepActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.jDialogDepartamento.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int row = this.jTableDep.getSelectedRow();
            if (row != -1) {
                String id = (String) jTableDep.getValueAt(row, 0);
                String modelo = (String) jTableDep.getValueAt(row, 1);
                this.txtDep.setText(id);
                this.jDialogDepartamento.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione una Fila!!", "Atencion", JOptionPane.INFORMATION_MESSAGE);

            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDepKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDepKeyTyped
        Funciones.valCampoNit(evt, this.txtDep.getText());
    }//GEN-LAST:event_txtDepKeyTyped
    private void mostarDepartamento() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID_DEPARTAMENTO");
        model.addColumn("DEPARTAMENTO");
        try {
            stmt = cn.createStatement();
            qry = "Select ID_DEPARTAMENTO,DESCRIPCION FROM DEPARTAMENTO WHERE ESTADO='1' ORDER BY ID_DEPARTAMENTO";
            ResultSet rs = stmt.executeQuery(qry);
            while (rs.next()) {
                Object[] fila = new Object[model.getColumnCount()];
                for (int i = 0; i < fila.length; i++) {
                    fila[i] = rs.getString(i + 1);

                }
                model.addRow(fila);
            }
            this.jTableDep.setModel(model);
        } catch (SQLException ex) {
        }
        this.jDialogDepartamento.show();
    }

    private void obtenerId() {
        try {

            stmt = cn.createStatement();
            qry = AppConstasQry.qryMaxEmpleado;
            r = stmt.executeQuery(qry);

            if (r.next()) {
                txtId.setText(r.getString(1));
            }
        } catch (SQLException e) {
        }
    }

    private void mostrarDatos() {
        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID_EMPLEADO");
        model.addColumn("PRIMER_NOMBRE");
        model.addColumn("SEGUNDO_NOMBRE");
        model.addColumn("PRIMER_APELLIDO");
        model.addColumn("SEGUNDO_APELLIDO");
        model.addColumn("NIT");
        model.addColumn("SALARIO");
        model.addColumn("ID_DEPARTAMENTO");
        try {
            stmt = cn.createStatement();
            qry = "Select ID_EMPLEADO,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,NIT,SALARIO,ID_DEPARTAMENTO FROM EMPLEADO where ESTATUS='1' ORDER BY ID_EMPLEADO";
            ResultSet rs = stmt.executeQuery(qry);
            while (rs.next()) {
                Object[] fila = new Object[model.getColumnCount()];
                for (int i = 0; i < fila.length; i++) {

                    fila[i] = rs.getString(i + 1);

                }
                model.addRow(fila);
            }
            this.jTableEmpleado.setModel(model);
        } catch (SQLException ex) {
        }
    }

    private void insertarEmpleado() {
        String id = txtId.getText(), nombre1 = txtNombre1.getText(), nombre2 = txtNombre2.getText(), apellido1 = txtApellido1.getText(), apellido2 = txtApellido2.getText();
        String nit = txtNit.getText(), salario = txtSalario.getText();
        String idDep = txtDep.getText();

        try {
            cts = cn.prepareCall("{call INSERTAR_EMPLEADO(?,?,?,?,?,?,?,?,?)}");
            cts.setInt(1, Integer.parseInt(id));
            cts.setString(2, nombre1);
            cts.setString(3, nombre2);
            cts.setString(4, apellido1);
            cts.setString(5, apellido2);
            cts.setString(6, nit);
            cts.setInt(7, Integer.parseInt(salario));
            cts.setInt(8, 1);
            cts.setInt(9, Integer.parseInt(idDep));

            int rpta = cts.executeUpdate();
            if (rpta == 1) {
                JOptionPane.showMessageDialog(this, "Empleado Registrado correctamente!!", "Atencion", JOptionPane.INFORMATION_MESSAGE);

            }
            desabilitar();
            limpiar();
            btnNuevo.setEnabled(true);
            btnGuardar.setEnabled(false);
            btnBuscar.setEnabled(true);
            btnBuscarDep.setEnabled(false);
            this.btnCancelar.setEnabled(false);
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }

    private void buscarEmpleado() {
        String cod = JOptionPane.showInputDialog("INGRESE EL CODIGO DEL EMPLEADO A BUSCAR");
        try {
            stmt = cn.createStatement();
            qry = "SELECT ID_EMPLEADO,PRIMER_NOMBRE,SEGUNDO_NOMBRE,PRIMER_APELLIDO,SEGUNDO_APELLIDO,NIT,SALARIO,ID_DEPARTAMENTO"
                    + " FROM USUARIO_JAVA.EMPLEADO"
                    + " WHERE ID_EMPLEADO = " + Integer.parseInt(cod) + " AND ESTATUS=1";
            r = stmt.executeQuery(qry);

            if (r.next()) {
                JOptionPane.showMessageDialog(this, "Empleado Encontrado!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                this.txtId.setText(r.getString(1));
                this.txtNombre1.setText(r.getString(2));
                this.txtNombre2.setText(r.getString(3));
                this.txtApellido1.setText(r.getString(4));
                this.txtApellido2.setText(r.getString(5));
                this.txtNit.setText(r.getString(6));
                this.txtSalario.setText(r.getString(7));
                this.txtDep.setText(r.getString(8));

                this.btnNuevo.setEnabled(false);
                this.btnGuardar.setEnabled(false);
                this.btnBuscar.setEnabled(false);
                this.btnModificar.setEnabled(true);
                this.btnEliminar.setEnabled(true);
                this.btnCancelar.setEnabled(true);
                this.btnBuscarDep.setEnabled(true);
                habilitar();
            } else {
                JOptionPane.showMessageDialog(this, "Empleado  No Encontrado!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }

    private void modificarEmpleado() {
        String id = txtId.getText(), nombre1 = txtNombre1.getText(), nombre2 = txtNombre2.getText(), apellido1 = txtApellido1.getText(), apellido2 = txtApellido2.getText();
        String nit = txtNit.getText(), salario = txtSalario.getText();
        String idDep = txtDep.getText();

        try {
            cts = cn.prepareCall("{call ACTUALIZAR_EMPLEADO(?,?,?,?,?,?,?,?)}");
            cts.setInt(1, Integer.parseInt(id));
            cts.setString(2, nombre1);
            cts.setString(3, nombre2);
            cts.setString(4, apellido1);
            cts.setString(5, apellido2);
            cts.setString(6, nit);
            cts.setInt(7, Integer.parseInt(salario));
            cts.setInt(8, Integer.parseInt(idDep));

            int rpta = cts.executeUpdate();
            if (rpta == 1) {
                JOptionPane.showMessageDialog(this, "Empleado Modificado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
                desabilitar();
                this.btnBuscar.setEnabled(true);
                this.btnNuevo.setEnabled(true);
                this.btnModificar.setEnabled(false);
                this.btnEliminar.setEnabled(false);
                this.btnCancelar.setEnabled(false);
                this.btnBuscarDep.setEnabled(false);
                mostrarDatos();
            } else {

                JOptionPane.showMessageDialog(this, "Error al modificar", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }

    private void eliminarEmpleado() {
        String cod = this.txtId.getText();
        try {
            cts = cn.prepareCall("{call ELIMINAR_EMPLEADO(?,?)}");
            cts.setInt(1, Integer.parseInt(cod));
            cts.setInt(2, 0);
            int rpta = cts.executeUpdate();

            if (rpta == 1) {
                JOptionPane.showMessageDialog(this, "EMPLEADO Eliminado", "Aviso", JOptionPane.INFORMATION_MESSAGE);

                limpiar();
                desabilitar();
                this.btnBuscar.setEnabled(true);
                this.btnNuevo.setEnabled(true);
                this.btnModificar.setEnabled(false);
                this.btnEliminar.setEnabled(false);
                this.btnCancelar.setEnabled(false);
                this.btnBuscarDep.setEnabled(false);
                mostrarDatos();
            } else {
                JOptionPane.showMessageDialog(this, "EMPLEADO No Eliminado", "Aviso", JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void limpiar() {
        this.txtId.setText("");
        this.txtNombre1.setText("");
        this.txtNombre2.setText("");
        this.txtApellido1.setText("");
        this.txtApellido2.setText("");
        this.txtNit.setText("");
        this.txtSalario.setText("");
        this.txtDep.setText("");
    }

    private void habilitar() {
        this.txtId.setEnabled(false);
        this.txtNombre1.setEnabled(true);
        this.txtNombre2.setEnabled(true);
        this.txtApellido1.setEnabled(true);
        this.txtApellido2.setEnabled(true);
        this.txtNit.setEnabled(true);
        this.txtSalario.setEnabled(true);
        this.txtDep.setEnabled(true);
    }

    private void desabilitar() {
        this.txtId.setEnabled(false);
        this.txtNombre1.setEnabled(false);
        this.txtNombre2.setEnabled(false);
        this.txtApellido1.setEnabled(false);
        this.txtApellido2.setEnabled(false);
        this.txtNit.setEnabled(false);
        this.txtSalario.setEnabled(false);
        this.txtDep.setEnabled(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarDep;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialogDepartamento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDep;
    private javax.swing.JTable jTableEmpleado;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDire;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lvlApellido;
    private javax.swing.JLabel lvlApellido1;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtDep;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtSalario;
    // End of variables declaration//GEN-END:variables
}
