/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import conexion.CreateConnection;
import java.awt.HeadlessException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JairoDev
 */
public class Proveedor extends javax.swing.JFrame {
    Connection cn;
    CallableStatement cts;
    ResultSet r;
    CreateConnection conectar = new CreateConnection();
    Vector columnNames = new Vector();
    Vector data = new Vector();
    Statement stmt;
    String qry = null;

    /**
     * Creates new form Proveedor
     */
    DefaultTableModel modelo = new DefaultTableModel();
    public Proveedor() throws SQLException {
        initComponents();
        this.stmt = null;
        this.jTableProveedor.setModel(modelo);
        cn = conectar.getConnection();
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProveedor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPais = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtContacto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTelContacto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProveedor);

        jLabel1.setText("ID_PROVEEDOR");

        txtId.setEnabled(false);

        jLabel2.setText("Empresa");

        txtEmpresa.setEnabled(false);

        jLabel3.setText("Direccion");

        txtDireccion.setEnabled(false);

        jLabel4.setText("Telefono");

        txtTelefono.setEnabled(false);

        jLabel5.setText("Nit");

        txtNit.setEnabled(false);

        txtCiudad.setEnabled(false);

        jLabel6.setText("Ciudad");

        txtPais.setEnabled(false);

        jLabel7.setText("Pais");

        txtContacto.setEnabled(false);

        jLabel8.setText("Contacto");

        txtEmail.setEnabled(false);

        jLabel9.setText("Email");

        txtTelContacto.setEnabled(false);
        txtTelContacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelContactoActionPerformed(evt);
            }
        });

        jLabel10.setText("Telefono Cont");

        btnNuevo.setText("Nuevo");
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
        });
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.setEnabled(false);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(685, 685, 685))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(388, 388, 388))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtTelContacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelContactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelContactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelContactoActionPerformed

    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked

    }//GEN-LAST:event_btnNuevoMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
        obtenerId();
        habilitar();
        btnNuevo.setEnabled(false);
        btnGuardar.setEnabled(true);
        btnBuscar.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked

    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        insertarProveedor();
        mostrarDatos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        String cod = JOptionPane.showInputDialog("INGRESE EL CODIGO DEL PROVEEDOR A BUSCAR");
        try {
            stmt = cn.createStatement();
            qry = "SELECT ID_PROVEEDOR,EMPRESA,DIRECCION,TELEFONO,NIT,CIUDAD,PAIS,CONTACTO,EMAIL,TELEFONO_CONTACTO,ESTATUS"
            + " FROM USUARIO_JAVA.PROVEEDOR"
            + " WHERE ID_PROVEEDOR = "+Integer.parseInt(cod);
            r =stmt.executeQuery(qry);

            if (r.next()) {
                JOptionPane.showMessageDialog(this, "Proveedor Encontrado!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                this.txtId.setText(r.getString(1));
                this.txtEmpresa.setText(r.getString(2));
                this.txtDireccion.setText(r.getString(3));
                this.txtTelefono.setText(r.getString(4));
                this.txtNit.setText(r.getString(5));
                this.txtCiudad.setText(r.getString(6));
                this.txtPais.setText(r.getString(7));
                this.txtContacto.setText(r.getString(8));
                this.txtEmail.setText(r.getString(9));
                this.txtTelContacto.setText(r.getString(10));

                //Habilitar();
                this.btnNuevo.setEnabled(false);
                this.btnGuardar.setEnabled(false);
                this.btnBuscar.setEnabled(false);
                this.btnModificar.setEnabled(true);
                this.btnEliminar.setEnabled(true);
                habilitar();
            } else {
                JOptionPane.showMessageDialog(this, "DEPARTAMENTO  No Encontrado!!", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String id=txtId.getText(), empresa = txtEmpresa.getText(), direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText(), nit = txtNit.getText(), ciudad = txtCiudad.getText();
        String pais = txtPais.getText(), contacto = txtContacto.getText(), email = txtEmail.getText(), telcont=this.txtTelContacto.getText();

        try {
            cts = cn.prepareCall("{call ACTUALIZAR_PROVEEDOR(?,?,?,?,?,?,?,?,?,?)}");
            cts.setString(1, id);
            cts.setString(2, empresa);
            cts.setString(3, direccion);
            cts.setString(4, direccion);


            int rpta = cts.executeUpdate();
            if (rpta == 1) {
                JOptionPane.showMessageDialog(this, "Departamento Modificado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                limpiar();
                desabilitar();
                this.btnBuscar.setEnabled(true);
                this.btnNuevo.setEnabled(true);
                this.btnModificar.setEnabled(false);
                this.btnEliminar.setEnabled(false);
                mostrarDatos();
            } else {

                JOptionPane.showMessageDialog(this, "Error al modificar", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String cod = this.txtId.getText();
        try {
            cts = cn.prepareCall("{call ELIMINAR_DEPARTAMENTO(?)}");
            cts.setString(1, cod);
            int rpta = cts.executeUpdate();

            if (rpta == 1) {
                JOptionPane.showMessageDialog(this, "DEPARTAMENTO Eliminado", "Aviso", JOptionPane.INFORMATION_MESSAGE);

                limpiar();
                desabilitar();
                this.btnBuscar.setEnabled(true);
                this.btnNuevo.setEnabled(true);
                this.btnModificar.setEnabled(false);
                this.btnEliminar.setEnabled(false);
                mostrarDatos();
            } else {
                JOptionPane.showMessageDialog(this, "Departamento No Eliminado", "Aviso", JOptionPane.INFORMATION_MESSAGE);

            }

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Proveedor().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Proveedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProveedor;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtContacto;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNit;
    private javax.swing.JTextField txtPais;
    private javax.swing.JTextField txtTelContacto;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

    private void mostrarDatos() {
        DefaultTableModel model = new DefaultTableModel();
      
       model.addColumn("ID_PROVEEDOR");
       model.addColumn("EMPRESA");  
       model.addColumn("DIRECCION");
       model.addColumn("TELEFONO");
       model.addColumn("NIT");
       model.addColumn("CIUDAD");
       model.addColumn("PAIS");
       model.addColumn("CONTACTO");
       model.addColumn("EMAIL");
       model.addColumn("TELEFONO_CONTACTO");
       model.addColumn("ESTATUS");
         try { 
            stmt=cn.createStatement();
            qry="Select * from PROVEEDOR where ESTATUS='1'";
            ResultSet  rs = stmt.executeQuery(qry);
            while (rs.next()) {
                Object[] fila = new Object[model.getColumnCount()];
                for (int i = 0; i < fila.length; i++) {
                  fila[i]=rs.getString(i+1);
                }
                model.addRow(fila);
               }           
            this.jTableProveedor.setModel(model);
       } catch (Exception ex) {
        ex.printStackTrace();
       }
    }

    private void limpiar() {
        this.txtId.setText("");
        this.txtEmpresa.setText("");
        this.txtDireccion.setText("");
        this.txtTelefono.setText("");
        this.txtNit.setText("");
        this.txtCiudad.setText("");
        this.txtPais.setText("");
        this.txtContacto.setText("");
        this.txtEmail.setText("");
        this.txtTelContacto.setText("");
    }

    private void obtenerId() {
       try{
            
            stmt = cn.createStatement();
            qry = "select coalesce(MAX(id_proveedor), 0)+1 id "
                    + "from proveedor";
            r =stmt.executeQuery(qry);

            if (r.next()) {
                txtId.setText(r.getString(1));
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    private void habilitar() {
        this.txtId.setEnabled(false);
        this.txtEmpresa.setEnabled(true);
        this.txtDireccion.setEnabled(true);
        this.txtTelefono.setEnabled(true);
        this.txtNit.setEnabled(true);
        this.txtCiudad.setEnabled(true);
        this.txtPais.setEnabled(true);
        this.txtContacto.setEnabled(true);
        this.txtEmail.setEnabled(true);
        this.txtTelContacto.setEnabled(true);
    }

    private void desabilitar() {
        this.txtId.setEnabled(false);
        this.txtEmpresa.setEnabled(false);
        this.txtDireccion.setEnabled(false);
        this.txtTelefono.setEnabled(false);
        this.txtNit.setEnabled(false);
        this.txtCiudad.setEnabled(false);
        this.txtPais.setEnabled(false);
        this.txtContacto.setEnabled(false);
        this.txtEmail.setEnabled(false);
        this.txtTelContacto.setEnabled(false);
    }

    private void insertarProveedor() {
        String id=txtId.getText(), empresa = txtEmpresa.getText(), direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText(), nit = txtNit.getText(), ciudad = txtCiudad.getText();
        String pais = txtPais.getText(), contacto = txtContacto.getText(), email = txtEmail.getText(), telcont=this.txtTelContacto.getText();
        
        try{
            cts = cn.prepareCall("{call insertar_proveedor(?,?,?,?,?,?,?,?,?,?,?)}");
            cts.setInt(1, Integer.parseInt(id));
            cts.setString(2, empresa);
            cts.setString(3,direccion);
            cts.setInt(4, Integer.parseInt(telefono));
            cts.setString(5, nit);
            cts.setString(6, ciudad);
            cts.setString(7, pais);
            cts.setString(8, contacto);
            cts.setString(9, email);
            cts.setInt(10, Integer.parseInt(telcont));
            cts.setInt(11,1);
            

            int rpta = cts.executeUpdate();
            if (rpta == 1) {
                JOptionPane.showMessageDialog(this, "Proveedor Registrado correctamente!!", "Atencion", JOptionPane.INFORMATION_MESSAGE);
                
            }
            desabilitar();
            limpiar();
            btnNuevo.setEnabled(true);
            btnGuardar.setEnabled(false);
            btnBuscar.setEnabled(true);
        }catch(Exception e){
            e.printStackTrace();
        }
    }
}
